// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace CrossCutting.Utilities.Parsers.Builders.Extensions
{
    public static partial class FunctionDescriptorArgumentBuilderExtensions
    {
        public static T WithName<T>(this T instance, string name)
            where T : CrossCutting.Utilities.Parsers.Builders.Abstractions.IFunctionDescriptorArgumentBuilder
        {
            if (name is null) throw new System.ArgumentNullException(nameof(name));
            instance.Name = name;
            return instance;
        }

        public static T WithDescription<T>(this T instance, string description)
            where T : CrossCutting.Utilities.Parsers.Builders.Abstractions.IFunctionDescriptorArgumentBuilder
        {
            if (description is null) throw new System.ArgumentNullException(nameof(description));
            instance.Description = description;
            return instance;
        }

        public static T WithIsRequired<T>(this T instance, bool isRequired = true)
            where T : CrossCutting.Utilities.Parsers.Builders.Abstractions.IFunctionDescriptorArgumentBuilder
        {
            instance.IsRequired = isRequired;
            return instance;
        }
    }
}
#nullable disable
