// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.6
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace CrossCutting.Utilities.QueryEvaluator.Expressions
{
    public partial record FieldNameExpression : CrossCutting.Utilities.QueryEvaluator.ExpressionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.IExpression
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public string FieldName
        {
            get;
        }

        public FieldNameExpression(string fieldName) : base()
        {
            this.FieldName = fieldName;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public override CrossCutting.Utilities.QueryEvaluator.Builders.ExpressionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Builders.Expressions.FieldNameExpressionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Builders.Expressions.FieldNameExpressionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IExpressionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.IExpression.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record LiteralExpression : CrossCutting.Utilities.QueryEvaluator.ExpressionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.IExpression
    {
        public object? Value
        {
            get;
        }

        public LiteralExpression(object? value) : base()
        {
            this.Value = value;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public override CrossCutting.Utilities.QueryEvaluator.Builders.ExpressionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Builders.Expressions.LiteralExpressionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Builders.Expressions.LiteralExpressionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IExpressionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.IExpression.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
}
#nullable disable
