// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.6
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace CrossCutting.Utilities.QueryEvaluator.Builders.Operators
{
    public partial class EqualsOperatorBuilder : OperatorBuilder<EqualsOperatorBuilder, CrossCutting.Utilities.QueryEvaluator.Operators.EqualsOperator>
    {
        private System.StringComparison _stringComparison;

        public System.StringComparison StringComparison
        {
            get
            {
                return _stringComparison;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.StringComparison>.Default.Equals(_stringComparison, value);
                _stringComparison = value;
                if (hasChanged) HandlePropertyChanged(nameof(StringComparison));
            }
        }

        public EqualsOperatorBuilder(CrossCutting.Utilities.QueryEvaluator.Operators.EqualsOperator source) : base(source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            _stringComparison = source.StringComparison;
        }

        public EqualsOperatorBuilder() : base()
        {
            SetDefaultValues();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Operators.EqualsOperator BuildTyped()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Operators.EqualsOperator(StringComparison);
        }

        partial void SetDefaultValues();

        public CrossCutting.Utilities.QueryEvaluator.Builders.Operators.EqualsOperatorBuilder WithStringComparison(System.StringComparison stringComparison)
        {
            StringComparison = stringComparison;
            return this;
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Operators.EqualsOperator(EqualsOperatorBuilder entity)
        {
            return entity.BuildTyped();
        }
    }
}
#nullable disable
