// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.10
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace CrossCutting.Utilities.ExpressionEvaluator.Builders
{
    public abstract partial class EvaluatableBaseBuilder : CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IEvaluatableBuilder, System.ComponentModel.INotifyPropertyChanged
    {
        public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;

        protected EvaluatableBaseBuilder(CrossCutting.Utilities.ExpressionEvaluator.EvaluatableBase source)
        {
        }

        protected EvaluatableBaseBuilder()
        {
            SetDefaultValues();
        }

        public abstract CrossCutting.Utilities.ExpressionEvaluator.EvaluatableBase Build();

        partial void SetDefaultValues();

        public static implicit operator CrossCutting.Utilities.ExpressionEvaluator.EvaluatableBase(EvaluatableBaseBuilder builder)
        {
            return builder.Build();
        }

        protected void HandlePropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}
#nullable disable
