// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.8
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace CrossCutting.Utilities.QueryEvaluator.Core.Builders
{
    public partial class QueryParameterBuilder : System.ComponentModel.INotifyPropertyChanged
    {
        private string _name;

        private object? _value;

        public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.String>.Default.Equals(_name!, value!);
                _name = value ?? throw new System.ArgumentNullException(nameof(value));
                if (hasChanged) HandlePropertyChanged(nameof(Name));
            }
        }

        public object? Value
        {
            get
            {
                return _value;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.Object>.Default.Equals(_value!, value!);
                _value = value;
                if (hasChanged) HandlePropertyChanged(nameof(Value));
            }
        }

        public QueryParameterBuilder(CrossCutting.Utilities.QueryEvaluator.Core.QueryParameter source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            _name = source.Name;
            _value = source.Value;
        }

        public QueryParameterBuilder()
        {
            _name = string.Empty;
            SetDefaultValues();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.QueryParameter Build()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.QueryParameter(Name, Value);
        }

        partial void SetDefaultValues();

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.QueryParameterBuilder WithName(string name)
        {
            if (name is null) throw new System.ArgumentNullException(nameof(name));
            Name = name;
            return this;
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.QueryParameterBuilder WithValue(object? value)
        {
            Value = value;
            return this;
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.QueryParameter(QueryParameterBuilder builder)
        {
            return builder.Build();
        }

        protected void HandlePropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    public partial class QueryParameterValueBuilder : System.ComponentModel.INotifyPropertyChanged
    {
        private string _name;

        public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.String>.Default.Equals(_name!, value!);
                _name = value ?? throw new System.ArgumentNullException(nameof(value));
                if (hasChanged) HandlePropertyChanged(nameof(Name));
            }
        }

        public QueryParameterValueBuilder(CrossCutting.Utilities.QueryEvaluator.Core.QueryParameterValue source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            _name = source.Name;
        }

        public QueryParameterValueBuilder()
        {
            _name = string.Empty;
            SetDefaultValues();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.QueryParameterValue Build()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.QueryParameterValue(Name);
        }

        partial void SetDefaultValues();

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.QueryParameterValueBuilder WithName(string name)
        {
            if (name is null) throw new System.ArgumentNullException(nameof(name));
            Name = name;
            return this;
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.QueryParameterValue(QueryParameterValueBuilder builder)
        {
            return builder.Build();
        }

        protected void HandlePropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    public partial class SortOrderBuilder : CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISortOrderBuilder, System.ComponentModel.INotifyPropertyChanged
    {
        private CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IExpressionBuilder _expression;

        private CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.SortOrderDirection _order;

        public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IExpressionBuilder Expression
        {
            get
            {
                return _expression;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IExpressionBuilder>.Default.Equals(_expression!, value!);
                _expression = value ?? throw new System.ArgumentNullException(nameof(value));
                if (hasChanged) HandlePropertyChanged(nameof(Expression));
            }
        }

        public CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.SortOrderDirection Order
        {
            get
            {
                return _order;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.SortOrderDirection>.Default.Equals(_order, value);
                _order = value;
                if (hasChanged) HandlePropertyChanged(nameof(Order));
            }
        }

        public SortOrderBuilder(CrossCutting.Utilities.QueryEvaluator.Core.SortOrder source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            _expression = source.Expression?.ToBuilder()!;
            _order = source.Order;
        }

        public SortOrderBuilder()
        {
            _expression = default(CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IExpressionBuilder)!;
            SetDefaultValues();
        }

        public CrossCutting.Utilities.QueryEvaluator.Abstractions.ISortOrder Build()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.SortOrder(Expression?.Build()!, Order);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.ISortOrder CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISortOrderBuilder.Build()
        {
            return Build();
        }

        partial void SetDefaultValues();

        protected void HandlePropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}
#nullable disable
