// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.3
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallArguments
{
    public partial class ConstantArgumentBuilder : FunctionCallArgumentBaseBuilder<ConstantArgumentBuilder, CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantArgument>, CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder
    {
        private object? _value;

        public object? Value
        {
            get
            {
                return _value;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.Object>.Default.Equals(_value!, value!);
                _value = value;
                if (hasChanged) HandlePropertyChanged(nameof(Value));
            }
        }

        public ConstantArgumentBuilder(CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantArgument source) : base(source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            _value = source.Value;
        }

        public ConstantArgumentBuilder() : base()
        {
            SetDefaultValues();
        }

        public override CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantArgument BuildTyped()
        {
            return new CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantArgument(Value);
        }

        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IFunctionCallArgument CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder.Build()
        {
            return BuildTyped();
        }

        partial void SetDefaultValues();

        public CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallArguments.ConstantArgumentBuilder WithValue(object? value)
        {
            Value = value;
            return this;
        }

        public static implicit operator CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantArgument(ConstantArgumentBuilder entity)
        {
            return entity.BuildTyped();
        }
    }
    public partial class ConstantArgumentBuilder<T> : FunctionCallArgumentBaseBuilder<ConstantArgumentBuilder<T>, CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantArgument<T>>, CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder, CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder<T>
    {
        private T _value;

        public T Value
        {
            get
            {
                return _value;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<T>.Default.Equals(_value!, value!);
                _value = value;
                if (hasChanged) HandlePropertyChanged(nameof(Value));
            }
        }

        public ConstantArgumentBuilder(CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantArgument<T> source) : base(source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            _value = source.Value;
        }

        public ConstantArgumentBuilder() : base()
        {
            _value = default(T)!;
            SetDefaultValues();
        }

        public override CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantArgument<T> BuildTyped()
        {
            return new CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantArgument<T>(Value);
        }

        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IFunctionCallArgument CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder.Build()
        {
            return BuildTyped();
        }

        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IFunctionCallArgument<T> CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder<T>.Build()
        {
            return BuildTyped();
        }

        partial void SetDefaultValues();

        public CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallArguments.ConstantArgumentBuilder<T> WithValue(T value)
        {
            Value = value;
            return this;
        }

        public static implicit operator CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantArgument<T>(ConstantArgumentBuilder<T> entity)
        {
            return entity.BuildTyped();
        }
    }
    public partial class ConstantResultArgumentBuilder : FunctionCallArgumentBaseBuilder<ConstantResultArgumentBuilder, CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantResultArgument>, CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder
    {
        private CrossCutting.Common.Results.Result<object?> _result;

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public CrossCutting.Common.Results.Result<object?> Result
        {
            get
            {
                return _result;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<CrossCutting.Common.Results.Result<System.Object?>>.Default.Equals(_result!, value!);
                _result = value ?? throw new System.ArgumentNullException(nameof(value));
                if (hasChanged) HandlePropertyChanged(nameof(Result));
            }
        }

        public ConstantResultArgumentBuilder(CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantResultArgument source) : base(source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            _result = source.Result;
        }

        public ConstantResultArgumentBuilder() : base()
        {
            _result = default(CrossCutting.Common.Results.Result<System.Object?>)!;
            SetDefaultValues();
        }

        public override CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantResultArgument BuildTyped()
        {
            return new CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantResultArgument(Result);
        }

        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IFunctionCallArgument CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder.Build()
        {
            return BuildTyped();
        }

        partial void SetDefaultValues();

        public CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallArguments.ConstantResultArgumentBuilder WithResult(CrossCutting.Common.Results.Result<object?> result)
        {
            if (result is null) throw new System.ArgumentNullException(nameof(result));
            Result = result;
            return this;
        }

        public static implicit operator CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantResultArgument(ConstantResultArgumentBuilder entity)
        {
            return entity.BuildTyped();
        }
    }
    public partial class ConstantResultArgumentBuilder<T> : FunctionCallArgumentBaseBuilder<ConstantResultArgumentBuilder<T>, CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantResultArgument<T>>, CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder, CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder<T>
    {
        private CrossCutting.Common.Results.Result<T> _result;

        public CrossCutting.Common.Results.Result<T> Result
        {
            get
            {
                return _result;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<CrossCutting.Common.Results.Result<T>>.Default.Equals(_result!, value!);
                _result = value ?? throw new System.ArgumentNullException(nameof(value));
                if (hasChanged) HandlePropertyChanged(nameof(Result));
            }
        }

        public ConstantResultArgumentBuilder(CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantResultArgument<T> source) : base(source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            _result = source.Result;
        }

        public ConstantResultArgumentBuilder() : base()
        {
            _result = default(CrossCutting.Common.Results.Result<T>)!;
            SetDefaultValues();
        }

        public override CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantResultArgument<T> BuildTyped()
        {
            return new CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantResultArgument<T>(Result);
        }

        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IFunctionCallArgument CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder.Build()
        {
            return BuildTyped();
        }

        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IFunctionCallArgument<T> CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder<T>.Build()
        {
            return BuildTyped();
        }

        partial void SetDefaultValues();

        public CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallArguments.ConstantResultArgumentBuilder<T> WithResult(CrossCutting.Common.Results.Result<T> result)
        {
            if (result is null) throw new System.ArgumentNullException(nameof(result));
            Result = result;
            return this;
        }

        public static implicit operator CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ConstantResultArgument<T>(ConstantResultArgumentBuilder<T> entity)
        {
            return entity.BuildTyped();
        }
    }
    public partial class DelegateArgumentBuilder : FunctionCallArgumentBaseBuilder<DelegateArgumentBuilder, CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateArgument>, CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder
    {
        private System.Func<object?> _delegate;

        private System.Func<System.Type>? _validationDelegate;

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public System.Func<object?> Delegate
        {
            get
            {
                return _delegate;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.Func<System.Object?>>.Default.Equals(_delegate!, value!);
                _delegate = value ?? throw new System.ArgumentNullException(nameof(value));
                if (hasChanged) HandlePropertyChanged(nameof(Delegate));
            }
        }

        public System.Func<System.Type>? ValidationDelegate
        {
            get
            {
                return _validationDelegate;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.Func<System.Type>?>.Default.Equals(_validationDelegate!, value!);
                _validationDelegate = value;
                if (hasChanged) HandlePropertyChanged(nameof(ValidationDelegate));
            }
        }

        public DelegateArgumentBuilder(CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateArgument source) : base(source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            _delegate = source.Delegate;
            _validationDelegate = source.ValidationDelegate;
        }

        public DelegateArgumentBuilder() : base()
        {
            _delegate = default(System.Func<System.Object?>)!;
            SetDefaultValues();
        }

        public override CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateArgument BuildTyped()
        {
            return new CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateArgument(Delegate, ValidationDelegate);
        }

        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IFunctionCallArgument CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder.Build()
        {
            return BuildTyped();
        }

        partial void SetDefaultValues();

        public CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallArguments.DelegateArgumentBuilder WithDelegate(System.Func<object?> @delegate)
        {
            if (@delegate is null) throw new System.ArgumentNullException(nameof(@delegate));
            Delegate = @delegate;
            return this;
        }

        public CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallArguments.DelegateArgumentBuilder WithValidationDelegate(System.Func<System.Type>? validationDelegate)
        {
            ValidationDelegate = validationDelegate;
            return this;
        }

        public static implicit operator CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateArgument(DelegateArgumentBuilder entity)
        {
            return entity.BuildTyped();
        }
    }
    public partial class DelegateArgumentBuilder<T> : FunctionCallArgumentBaseBuilder<DelegateArgumentBuilder<T>, CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateArgument<T>>, CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder, CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder<T>
    {
        private System.Func<T> _delegate;

        private System.Func<System.Type>? _validationDelegate;

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public System.Func<T> Delegate
        {
            get
            {
                return _delegate;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.Func<T>>.Default.Equals(_delegate!, value!);
                _delegate = value ?? throw new System.ArgumentNullException(nameof(value));
                if (hasChanged) HandlePropertyChanged(nameof(Delegate));
            }
        }

        public System.Func<System.Type>? ValidationDelegate
        {
            get
            {
                return _validationDelegate;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.Func<System.Type>?>.Default.Equals(_validationDelegate!, value!);
                _validationDelegate = value;
                if (hasChanged) HandlePropertyChanged(nameof(ValidationDelegate));
            }
        }

        public DelegateArgumentBuilder(CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateArgument<T> source) : base(source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            _delegate = source.Delegate;
            _validationDelegate = source.ValidationDelegate;
        }

        public DelegateArgumentBuilder() : base()
        {
            _delegate = default(System.Func<T>)!;
            SetDefaultValues();
        }

        public override CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateArgument<T> BuildTyped()
        {
            return new CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateArgument<T>(Delegate, ValidationDelegate);
        }

        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IFunctionCallArgument CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder.Build()
        {
            return BuildTyped();
        }

        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IFunctionCallArgument<T> CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder<T>.Build()
        {
            return BuildTyped();
        }

        partial void SetDefaultValues();

        public CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallArguments.DelegateArgumentBuilder<T> WithDelegate(System.Func<T> @delegate)
        {
            if (@delegate is null) throw new System.ArgumentNullException(nameof(@delegate));
            Delegate = @delegate;
            return this;
        }

        public CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallArguments.DelegateArgumentBuilder<T> WithValidationDelegate(System.Func<System.Type>? validationDelegate)
        {
            ValidationDelegate = validationDelegate;
            return this;
        }

        public static implicit operator CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateArgument<T>(DelegateArgumentBuilder<T> entity)
        {
            return entity.BuildTyped();
        }
    }
    public partial class DelegateResultArgumentBuilder : FunctionCallArgumentBaseBuilder<DelegateResultArgumentBuilder, CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateResultArgument>, CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder
    {
        private System.Func<CrossCutting.Common.Results.Result<object?>> _delegate;

        private System.Func<CrossCutting.Common.Results.Result<System.Type>>? _validationDelegate;

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public System.Func<CrossCutting.Common.Results.Result<object?>> Delegate
        {
            get
            {
                return _delegate;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.Func<CrossCutting.Common.Results.Result<System.Object?>>>.Default.Equals(_delegate!, value!);
                _delegate = value ?? throw new System.ArgumentNullException(nameof(value));
                if (hasChanged) HandlePropertyChanged(nameof(Delegate));
            }
        }

        public System.Func<CrossCutting.Common.Results.Result<System.Type>>? ValidationDelegate
        {
            get
            {
                return _validationDelegate;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.Func<CrossCutting.Common.Results.Result<System.Type>>?>.Default.Equals(_validationDelegate!, value!);
                _validationDelegate = value;
                if (hasChanged) HandlePropertyChanged(nameof(ValidationDelegate));
            }
        }

        public DelegateResultArgumentBuilder(CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateResultArgument source) : base(source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            _delegate = source.Delegate;
            _validationDelegate = source.ValidationDelegate;
        }

        public DelegateResultArgumentBuilder() : base()
        {
            _delegate = default(System.Func<CrossCutting.Common.Results.Result<System.Object?>>)!;
            SetDefaultValues();
        }

        public override CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateResultArgument BuildTyped()
        {
            return new CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateResultArgument(Delegate, ValidationDelegate);
        }

        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IFunctionCallArgument CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder.Build()
        {
            return BuildTyped();
        }

        partial void SetDefaultValues();

        public CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallArguments.DelegateResultArgumentBuilder WithDelegate(System.Func<CrossCutting.Common.Results.Result<object?>> @delegate)
        {
            if (@delegate is null) throw new System.ArgumentNullException(nameof(@delegate));
            Delegate = @delegate;
            return this;
        }

        public CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallArguments.DelegateResultArgumentBuilder WithValidationDelegate(System.Func<CrossCutting.Common.Results.Result<System.Type>>? validationDelegate)
        {
            ValidationDelegate = validationDelegate;
            return this;
        }

        public static implicit operator CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateResultArgument(DelegateResultArgumentBuilder entity)
        {
            return entity.BuildTyped();
        }
    }
    public partial class DelegateResultArgumentBuilder<T> : FunctionCallArgumentBaseBuilder<DelegateResultArgumentBuilder<T>, CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateResultArgument<T>>, CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder, CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder<T>
    {
        private System.Func<CrossCutting.Common.Results.Result<T>> _delegate;

        private System.Func<CrossCutting.Common.Results.Result<System.Type>>? _validationDelegate;

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public System.Func<CrossCutting.Common.Results.Result<T>> Delegate
        {
            get
            {
                return _delegate;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.Func<CrossCutting.Common.Results.Result<T>>>.Default.Equals(_delegate!, value!);
                _delegate = value ?? throw new System.ArgumentNullException(nameof(value));
                if (hasChanged) HandlePropertyChanged(nameof(Delegate));
            }
        }

        public System.Func<CrossCutting.Common.Results.Result<System.Type>>? ValidationDelegate
        {
            get
            {
                return _validationDelegate;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.Func<CrossCutting.Common.Results.Result<System.Type>>?>.Default.Equals(_validationDelegate!, value!);
                _validationDelegate = value;
                if (hasChanged) HandlePropertyChanged(nameof(ValidationDelegate));
            }
        }

        public DelegateResultArgumentBuilder(CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateResultArgument<T> source) : base(source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            _delegate = source.Delegate;
            _validationDelegate = source.ValidationDelegate;
        }

        public DelegateResultArgumentBuilder() : base()
        {
            _delegate = default(System.Func<CrossCutting.Common.Results.Result<T>>)!;
            SetDefaultValues();
        }

        public override CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateResultArgument<T> BuildTyped()
        {
            return new CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateResultArgument<T>(Delegate, ValidationDelegate);
        }

        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IFunctionCallArgument CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder.Build()
        {
            return BuildTyped();
        }

        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IFunctionCallArgument<T> CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder<T>.Build()
        {
            return BuildTyped();
        }

        partial void SetDefaultValues();

        public CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallArguments.DelegateResultArgumentBuilder<T> WithDelegate(System.Func<CrossCutting.Common.Results.Result<T>> @delegate)
        {
            if (@delegate is null) throw new System.ArgumentNullException(nameof(@delegate));
            Delegate = @delegate;
            return this;
        }

        public CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallArguments.DelegateResultArgumentBuilder<T> WithValidationDelegate(System.Func<CrossCutting.Common.Results.Result<System.Type>>? validationDelegate)
        {
            ValidationDelegate = validationDelegate;
            return this;
        }

        public static implicit operator CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.DelegateResultArgument<T>(DelegateResultArgumentBuilder<T> entity)
        {
            return entity.BuildTyped();
        }
    }
    public partial class EmptyArgumentBuilder : FunctionCallArgumentBaseBuilder<EmptyArgumentBuilder, CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.EmptyArgument>, CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder
    {
        public EmptyArgumentBuilder(CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.EmptyArgument source) : base(source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
        }

        public EmptyArgumentBuilder() : base()
        {
            SetDefaultValues();
        }

        public override CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.EmptyArgument BuildTyped()
        {
            return new CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.EmptyArgument();
        }

        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IFunctionCallArgument CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder.Build()
        {
            return BuildTyped();
        }

        partial void SetDefaultValues();

        public static implicit operator CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.EmptyArgument(EmptyArgumentBuilder entity)
        {
            return entity.BuildTyped();
        }
    }
    public partial class EmptyArgumentBuilder<T> : FunctionCallArgumentBaseBuilder<EmptyArgumentBuilder<T>, CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.EmptyArgument<T>>, CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder, CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder<T>
    {
        public EmptyArgumentBuilder(CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.EmptyArgument<T> source) : base(source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
        }

        public EmptyArgumentBuilder() : base()
        {
            SetDefaultValues();
        }

        public override CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.EmptyArgument<T> BuildTyped()
        {
            return new CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.EmptyArgument<T>();
        }

        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IFunctionCallArgument CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder.Build()
        {
            return BuildTyped();
        }

        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IFunctionCallArgument<T> CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder<T>.Build()
        {
            return BuildTyped();
        }

        partial void SetDefaultValues();

        public static implicit operator CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.EmptyArgument<T>(EmptyArgumentBuilder<T> entity)
        {
            return entity.BuildTyped();
        }
    }
    public partial class ExpressionArgumentBuilder : FunctionCallArgumentBaseBuilder<ExpressionArgumentBuilder, CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ExpressionArgument>, CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder
    {
        private string _expression;

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public string Expression
        {
            get
            {
                return _expression;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.String>.Default.Equals(_expression!, value!);
                _expression = value ?? throw new System.ArgumentNullException(nameof(value));
                if (hasChanged) HandlePropertyChanged(nameof(Expression));
            }
        }

        public ExpressionArgumentBuilder(CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ExpressionArgument source) : base(source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            _expression = source.Expression;
        }

        public ExpressionArgumentBuilder() : base()
        {
            _expression = string.Empty;
            SetDefaultValues();
        }

        public override CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ExpressionArgument BuildTyped()
        {
            return new CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ExpressionArgument(Expression);
        }

        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IFunctionCallArgument CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder.Build()
        {
            return BuildTyped();
        }

        partial void SetDefaultValues();

        public CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallArguments.ExpressionArgumentBuilder WithExpression(string expression)
        {
            if (expression is null) throw new System.ArgumentNullException(nameof(expression));
            Expression = expression;
            return this;
        }

        public static implicit operator CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.ExpressionArgument(ExpressionArgumentBuilder entity)
        {
            return entity.BuildTyped();
        }
    }
    public partial class FunctionArgumentBuilder : FunctionCallArgumentBaseBuilder<FunctionArgumentBuilder, CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.FunctionArgument>, CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder
    {
        private CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallBuilder _function;

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallBuilder Function
        {
            get
            {
                return _function;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallBuilder>.Default.Equals(_function!, value!);
                _function = value ?? throw new System.ArgumentNullException(nameof(value));
                if (hasChanged) HandlePropertyChanged(nameof(Function));
            }
        }

        public FunctionArgumentBuilder(CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.FunctionArgument source) : base(source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            _function = source.Function.ToBuilder();
        }

        public FunctionArgumentBuilder() : base()
        {
            _function = new CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallBuilder()!;
            SetDefaultValues();
        }

        public override CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.FunctionArgument BuildTyped()
        {
            return new CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.FunctionArgument(Function.Build());
        }

        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IFunctionCallArgument CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IFunctionCallArgumentBuilder.Build()
        {
            return BuildTyped();
        }

        partial void SetDefaultValues();

        public CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallArguments.FunctionArgumentBuilder WithFunction(CrossCutting.Utilities.ExpressionEvaluator.Builders.FunctionCallBuilder function)
        {
            if (function is null) throw new System.ArgumentNullException(nameof(function));
            Function = function;
            return this;
        }

        public static implicit operator CrossCutting.Utilities.ExpressionEvaluator.FunctionCallArguments.FunctionArgument(FunctionArgumentBuilder entity)
        {
            return entity.BuildTyped();
        }
    }
}
#nullable disable
