// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 8.0.11
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace CrossCutting.Utilities.Parsers.Builders
{
    public abstract partial class FunctionParseResultArgumentBuilder : System.ComponentModel.INotifyPropertyChanged
    {
        public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;

        protected FunctionParseResultArgumentBuilder(CrossCutting.Utilities.Parsers.FunctionParseResultArgument source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
        }

        protected FunctionParseResultArgumentBuilder()
        {
            SetDefaultValues();
        }

        public abstract CrossCutting.Utilities.Parsers.FunctionParseResultArgument Build();

        partial void SetDefaultValues();

        protected void HandlePropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}
#nullable disable
