// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 8.0.11
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace CrossCutting.Utilities.Parsers.Builders
{
    public abstract partial class FunctionParseResultArgumentBuilder<TBuilder, TEntity> : FunctionParseResultArgumentBuilder
        where TEntity : CrossCutting.Utilities.Parsers.FunctionParseResultArgument
        where TBuilder : FunctionParseResultArgumentBuilder<TBuilder, TEntity>
    {
        protected FunctionParseResultArgumentBuilder(CrossCutting.Utilities.Parsers.FunctionParseResultArgument source) : base(source)
        {
        }

        protected FunctionParseResultArgumentBuilder() : base()
        {
        }

        public override CrossCutting.Utilities.Parsers.FunctionParseResultArgument Build()
        {
            return BuildTyped();
        }

        public abstract TEntity BuildTyped();
    }
}
#nullable disable
