// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.9
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace CrossCutting.Utilities.QueryEvaluator.QueryProcessors.Sql.Expressions.Builders
{
    public partial class SqlLikeExpressionBuilder : System.ComponentModel.INotifyPropertyChanged
    {
        private CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IExpressionBuilder _sourceExpression;

        private string _formatString;

        public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IExpressionBuilder SourceExpression
        {
            get
            {
                return _sourceExpression;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IExpressionBuilder>.Default.Equals(_sourceExpression!, value!);
                _sourceExpression = value ?? throw new System.ArgumentNullException(nameof(value));
                if (hasChanged) HandlePropertyChanged(nameof(SourceExpression));
            }
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public string FormatString
        {
            get
            {
                return _formatString;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.String>.Default.Equals(_formatString!, value!);
                _formatString = value ?? throw new System.ArgumentNullException(nameof(value));
                if (hasChanged) HandlePropertyChanged(nameof(FormatString));
            }
        }

        public SqlLikeExpressionBuilder(CrossCutting.Utilities.QueryEvaluator.QueryProcessors.Sql.Expressions.SqlLikeExpression source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            _sourceExpression = source.SourceExpression?.ToBuilder()!;
            _formatString = source.FormatString;
        }

        public SqlLikeExpressionBuilder()
        {
            _sourceExpression = default(CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IExpressionBuilder)!;
            _formatString = string.Empty;
            SetDefaultValues();
        }

        public CrossCutting.Utilities.QueryEvaluator.QueryProcessors.Sql.Expressions.SqlLikeExpression Build()
        {
            return new CrossCutting.Utilities.QueryEvaluator.QueryProcessors.Sql.Expressions.SqlLikeExpression(SourceExpression?.Build()!, FormatString);
        }

        partial void SetDefaultValues();

        public CrossCutting.Utilities.QueryEvaluator.QueryProcessors.Sql.Expressions.Builders.SqlLikeExpressionBuilder WithSourceExpression(CrossCutting.Utilities.ExpressionEvaluator.Builders.Abstractions.IExpressionBuilder sourceExpression)
        {
            if (sourceExpression is null) throw new System.ArgumentNullException(nameof(sourceExpression));
            SourceExpression = sourceExpression;
            return this;
        }

        public CrossCutting.Utilities.QueryEvaluator.QueryProcessors.Sql.Expressions.Builders.SqlLikeExpressionBuilder WithFormatString(string formatString)
        {
            if (formatString is null) throw new System.ArgumentNullException(nameof(formatString));
            FormatString = formatString;
            return this;
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.QueryProcessors.Sql.Expressions.SqlLikeExpression(SqlLikeExpressionBuilder builder)
        {
            return builder.Build();
        }

        protected void HandlePropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}
#nullable disable
