// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.3
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace CrossCutting.Utilities.QueryEvaluator.Core.Conditions
{
    public partial record BetweenCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.ITwoBoundariesExpressionContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable LowerBoundExpression
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable UpperBoundExpression
        {
            get;
        }

        public BetweenCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable lowerBoundExpression, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable upperBoundExpression) : base(combination, startGroup, endGroup)
        {
            this.SourceExpression = sourceExpression;
            this.LowerBoundExpression = lowerBoundExpression;
            this.UpperBoundExpression = upperBoundExpression;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.BetweenConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.BetweenCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.BetweenConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.BetweenConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ITwoBoundariesExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ITwoBoundariesExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record EqualCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable CompareExpression
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        public EqualCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable compareExpression, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression) : base(combination, startGroup, endGroup)
        {
            this.CompareExpression = compareExpression;
            this.SourceExpression = sourceExpression;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.EqualConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.EqualCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.EqualConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.EqualConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ICompareExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record GreaterThanCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable CompareExpression
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        public GreaterThanCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable compareExpression, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression) : base(combination, startGroup, endGroup)
        {
            this.CompareExpression = compareExpression;
            this.SourceExpression = sourceExpression;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.GreaterThanConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.GreaterThanCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.GreaterThanConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.GreaterThanConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ICompareExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record GreaterThanOrEqualCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable CompareExpression
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        public GreaterThanOrEqualCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable compareExpression, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression) : base(combination, startGroup, endGroup)
        {
            this.CompareExpression = compareExpression;
            this.SourceExpression = sourceExpression;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.GreaterThanOrEqualConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.GreaterThanOrEqualCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.GreaterThanOrEqualConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.GreaterThanOrEqualConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ICompareExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record InCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.IInCondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public System.Collections.Generic.IReadOnlyCollection<CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable> CompareExpressions
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        public InCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, System.Collections.Generic.IEnumerable<CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable> compareExpressions, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression) : base(combination, startGroup, endGroup)
        {
            this.CompareExpressions = compareExpressions is null ? null! : new CrossCutting.Common.ReadOnlyValueCollection<CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable>(compareExpressions);
            this.SourceExpression = sourceExpression;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.InConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.InCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.InConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.InConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IInConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.IInCondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record NotBetweenCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.ITwoBoundariesExpressionContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable LowerBoundExpression
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable UpperBoundExpression
        {
            get;
        }

        public NotBetweenCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable lowerBoundExpression, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable upperBoundExpression) : base(combination, startGroup, endGroup)
        {
            this.SourceExpression = sourceExpression;
            this.LowerBoundExpression = lowerBoundExpression;
            this.UpperBoundExpression = upperBoundExpression;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.NotBetweenConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.NotBetweenCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.NotBetweenConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.NotBetweenConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ITwoBoundariesExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ITwoBoundariesExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record NotEqualCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable CompareExpression
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        public NotEqualCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable compareExpression, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression) : base(combination, startGroup, endGroup)
        {
            this.CompareExpression = compareExpression;
            this.SourceExpression = sourceExpression;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.NotEqualConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.NotEqualCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.NotEqualConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.NotEqualConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ICompareExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record NotInCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.IInCondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public System.Collections.Generic.IReadOnlyCollection<CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable> CompareExpressions
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        public NotInCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, System.Collections.Generic.IEnumerable<CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable> compareExpressions, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression) : base(combination, startGroup, endGroup)
        {
            this.CompareExpressions = compareExpressions is null ? null! : new CrossCutting.Common.ReadOnlyValueCollection<CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable>(compareExpressions);
            this.SourceExpression = sourceExpression;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.NotInConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.NotInCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.NotInConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.NotInConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IInConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.IInCondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record NotNullCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        public NotNullCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression) : base(combination, startGroup, endGroup)
        {
            this.SourceExpression = sourceExpression;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.NotNullConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.NotNullCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.NotNullConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.NotNullConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record NullCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        public NullCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression) : base(combination, startGroup, endGroup)
        {
            this.SourceExpression = sourceExpression;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.NullConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.NullCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.NullConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.NullConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record SmallerThanCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable CompareExpression
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        public SmallerThanCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable compareExpression, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression) : base(combination, startGroup, endGroup)
        {
            this.CompareExpression = compareExpression;
            this.SourceExpression = sourceExpression;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.SmallerThanConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.SmallerThanCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.SmallerThanConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.SmallerThanConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ICompareExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record SmallerThanOrEqualCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable CompareExpression
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        public SmallerThanOrEqualCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable compareExpression, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression) : base(combination, startGroup, endGroup)
        {
            this.CompareExpression = compareExpression;
            this.SourceExpression = sourceExpression;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.SmallerThanOrEqualConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.SmallerThanOrEqualCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.SmallerThanOrEqualConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.SmallerThanOrEqualConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ICompareExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record StringContainsCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.IStringComparisonContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable CompareExpression
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        public System.StringComparison StringComparison
        {
            get;
        }

        public StringContainsCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable compareExpression, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression, System.StringComparison stringComparison) : base(combination, startGroup, endGroup)
        {
            this.CompareExpression = compareExpression;
            this.SourceExpression = sourceExpression;
            this.StringComparison = stringComparison;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringContainsConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.StringContainsCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringContainsConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringContainsConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ICompareExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IStringComparisonContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.IStringComparisonContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record StringEndsWithCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.IStringComparisonContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable CompareExpression
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        public System.StringComparison StringComparison
        {
            get;
        }

        public StringEndsWithCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable compareExpression, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression, System.StringComparison stringComparison) : base(combination, startGroup, endGroup)
        {
            this.CompareExpression = compareExpression;
            this.SourceExpression = sourceExpression;
            this.StringComparison = stringComparison;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringEndsWithConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.StringEndsWithCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringEndsWithConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringEndsWithConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ICompareExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IStringComparisonContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.IStringComparisonContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record StringEqualsCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.IStringComparisonContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable CompareExpression
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        public System.StringComparison StringComparison
        {
            get;
        }

        public StringEqualsCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable compareExpression, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression, System.StringComparison stringComparison) : base(combination, startGroup, endGroup)
        {
            this.CompareExpression = compareExpression;
            this.SourceExpression = sourceExpression;
            this.StringComparison = stringComparison;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringEqualsConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.StringEqualsCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringEqualsConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringEqualsConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ICompareExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IStringComparisonContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.IStringComparisonContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record StringNotContainsCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.IStringComparisonContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable CompareExpression
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        public System.StringComparison StringComparison
        {
            get;
        }

        public StringNotContainsCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable compareExpression, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression, System.StringComparison stringComparison) : base(combination, startGroup, endGroup)
        {
            this.CompareExpression = compareExpression;
            this.SourceExpression = sourceExpression;
            this.StringComparison = stringComparison;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringNotContainsConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.StringNotContainsCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringNotContainsConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringNotContainsConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ICompareExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IStringComparisonContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.IStringComparisonContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record StringNotEndsWithCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.IStringComparisonContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable CompareExpression
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        public System.StringComparison StringComparison
        {
            get;
        }

        public StringNotEndsWithCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable compareExpression, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression, System.StringComparison stringComparison) : base(combination, startGroup, endGroup)
        {
            this.CompareExpression = compareExpression;
            this.SourceExpression = sourceExpression;
            this.StringComparison = stringComparison;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringNotEndsWithConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.StringNotEndsWithCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringNotEndsWithConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringNotEndsWithConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ICompareExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IStringComparisonContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.IStringComparisonContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record StringNotEqualsCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.IStringComparisonContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable CompareExpression
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        public System.StringComparison StringComparison
        {
            get;
        }

        public StringNotEqualsCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable compareExpression, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression, System.StringComparison stringComparison) : base(combination, startGroup, endGroup)
        {
            this.CompareExpression = compareExpression;
            this.SourceExpression = sourceExpression;
            this.StringComparison = stringComparison;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringNotEqualsConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.StringNotEqualsCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringNotEqualsConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringNotEqualsConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ICompareExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IStringComparisonContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.IStringComparisonContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record StringNotStartsWithCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.IStringComparisonContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable CompareExpression
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        public System.StringComparison StringComparison
        {
            get;
        }

        public StringNotStartsWithCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable compareExpression, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression, System.StringComparison stringComparison) : base(combination, startGroup, endGroup)
        {
            this.CompareExpression = compareExpression;
            this.SourceExpression = sourceExpression;
            this.StringComparison = stringComparison;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringNotStartsWithConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.StringNotStartsWithCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringNotStartsWithConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringNotStartsWithConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ICompareExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IStringComparisonContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.IStringComparisonContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
    public partial record StringStartsWithCondition : CrossCutting.Utilities.QueryEvaluator.Core.ConditionBase, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer, CrossCutting.Utilities.QueryEvaluator.Abstractions.IStringComparisonContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable CompareExpression
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        public System.StringComparison StringComparison
        {
            get;
        }

        public StringStartsWithCondition(System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable compareExpression, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable sourceExpression, System.StringComparison stringComparison) : base(combination, startGroup, endGroup)
        {
            this.CompareExpression = compareExpression;
            this.SourceExpression = sourceExpression;
            this.StringComparison = stringComparison;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringStartsWithConditionBuilder(CrossCutting.Utilities.QueryEvaluator.Core.Conditions.StringStartsWithCondition entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.QueryEvaluator.Core.Builders.ConditionBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringStartsWithConditionBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.QueryEvaluator.Core.Builders.Conditions.StringStartsWithConditionBuilder(this);
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ICompareExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ICompareExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IStringComparisonContainerBuilder CrossCutting.Utilities.QueryEvaluator.Abstractions.IStringComparisonContainer.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
}
#nullable disable
