// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 7.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CrossCutting.Utilities.Parsers.Builders
{
#nullable enable
    public abstract partial class FunctionParseResultArgumentBuilder<TBuilder, TEntity> : FunctionParseResultArgumentBuilder
        where TEntity : CrossCutting.Utilities.Parsers.FunctionParseResultArgument
        where TBuilder : FunctionParseResultArgumentBuilder<TBuilder, TEntity>
    {
        public abstract TEntity BuildTyped();

        public override CrossCutting.Utilities.Parsers.FunctionParseResultArgument Build()
        {
            return BuildTyped();
        }

        protected FunctionParseResultArgumentBuilder() : base()
        {
        }

        protected FunctionParseResultArgumentBuilder(CrossCutting.Utilities.Parsers.FunctionParseResultArgument source) : base(source)
        {
        }
    }
#nullable restore
}

