// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 8.0.10
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace CrossCutting.Utilities.Parsers.Builders.FunctionParseResultArguments
{
    public partial class FunctionArgumentBuilder : CrossCutting.Utilities.Parsers.Builders.FunctionParseResultArgumentBuilder<FunctionArgumentBuilder, CrossCutting.Utilities.Parsers.FunctionParseResultArguments.FunctionArgument>
    {
        private CrossCutting.Utilities.Parsers.Builders.FunctionParseResultBuilder _function;

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public CrossCutting.Utilities.Parsers.Builders.FunctionParseResultBuilder Function
        {
            get
            {
                return _function;
            }
            set
            {
                _function = value ?? throw new System.ArgumentNullException(nameof(value));
                HandlePropertyChanged(nameof(Function));
            }
        }

        public FunctionArgumentBuilder(CrossCutting.Utilities.Parsers.FunctionParseResultArguments.FunctionArgument source) : base(source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            _function = source.Function.ToBuilder();
        }

        public FunctionArgumentBuilder() : base()
        {
            _function = new CrossCutting.Utilities.Parsers.Builders.FunctionParseResultBuilder()!;
            SetDefaultValues();
        }

        public override CrossCutting.Utilities.Parsers.FunctionParseResultArguments.FunctionArgument BuildTyped()
        {
            return new CrossCutting.Utilities.Parsers.FunctionParseResultArguments.FunctionArgument(Function.Build());
        }

        partial void SetDefaultValues();

        public CrossCutting.Utilities.Parsers.Builders.FunctionParseResultArguments.FunctionArgumentBuilder WithFunction(CrossCutting.Utilities.Parsers.Builders.FunctionParseResultBuilder function)
        {
            if (function is null) throw new System.ArgumentNullException(nameof(function));
            Function = function;
            return this;
        }
    }
    public partial class LiteralArgumentBuilder : CrossCutting.Utilities.Parsers.Builders.FunctionParseResultArgumentBuilder<LiteralArgumentBuilder, CrossCutting.Utilities.Parsers.FunctionParseResultArguments.LiteralArgument>
    {
        private string _value;

        public string Value
        {
            get
            {
                return _value;
            }
            set
            {
                _value = value ?? throw new System.ArgumentNullException(nameof(value));
                HandlePropertyChanged(nameof(Value));
            }
        }

        public LiteralArgumentBuilder(CrossCutting.Utilities.Parsers.FunctionParseResultArguments.LiteralArgument source) : base(source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            _value = source.Value;
        }

        public LiteralArgumentBuilder() : base()
        {
            _value = string.Empty;
            SetDefaultValues();
        }

        public override CrossCutting.Utilities.Parsers.FunctionParseResultArguments.LiteralArgument BuildTyped()
        {
            return new CrossCutting.Utilities.Parsers.FunctionParseResultArguments.LiteralArgument(Value);
        }

        partial void SetDefaultValues();

        public CrossCutting.Utilities.Parsers.Builders.FunctionParseResultArguments.LiteralArgumentBuilder WithValue(string value)
        {
            if (value is null) throw new System.ArgumentNullException(nameof(value));
            Value = value;
            return this;
        }
    }
}
#nullable disable
