// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.6
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace CrossCutting.Utilities.QueryEvaluator.Builders.Abstractions
{
    public partial interface IStringComparisonContainerBuilder
    {
        System.StringComparison StringComparison
        {
            get;
            set;
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.IStringComparisonContainer Build();
    }
}
#nullable disable
