// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.3
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace CrossCutting.Utilities.QueryEvaluator.Abstractions
{
    public partial interface ICompareExpressionContainer : CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable CompareExpression
        {
            get;
        }

        new CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ICompareExpressionContainerBuilder ToBuilder();
    }
    public partial interface ICondition
    {
        System.Nullable<CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.Combination> Combination
        {
            get;
        }

        bool StartGroup
        {
            get;
        }

        bool EndGroup
        {
            get;
        }

        new CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IConditionBuilder ToBuilder();
    }
    public partial interface IDataObjectNameQuery : CrossCutting.Utilities.QueryEvaluator.Abstractions.IQuery
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        string DataObjectName
        {
            get;
        }

        new CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IDataObjectNameQueryBuilder ToBuilder();
    }
    public partial interface IFieldSelectionQuery : CrossCutting.Utilities.QueryEvaluator.Abstractions.IQuery
    {
        bool Distinct
        {
            get;
        }

        bool GetAllFields
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        System.Collections.Generic.IReadOnlyCollection<string> FieldNames
        {
            get;
        }

        new CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IFieldSelectionQueryBuilder ToBuilder();
    }
    public partial interface IInCondition : CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition, CrossCutting.Utilities.QueryEvaluator.Abstractions.ISourceExpressionContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        System.Collections.Generic.IReadOnlyCollection<CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable> CompareExpressions
        {
            get;
        }

        new CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IInConditionBuilder ToBuilder();
    }
    public partial interface IQuery
    {
        System.Nullable<int> Limit
        {
            get;
        }

        System.Nullable<int> Offset
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        [CrossCutting.Utilities.QueryEvaluator.Abstractions.Validation.ValidGroupsAttribute]
        System.Collections.Generic.IReadOnlyCollection<CrossCutting.Utilities.QueryEvaluator.Abstractions.ICondition> Conditions
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        System.Collections.Generic.IReadOnlyCollection<CrossCutting.Utilities.QueryEvaluator.Abstractions.ISortOrder> SortOrders
        {
            get;
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IQueryBuilder ToBuilder();
    }
    public partial interface ISortOrder
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable Expression
        {
            get;
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Domains.SortOrderDirection Order
        {
            get;
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISortOrderBuilder ToBuilder();
    }
    public partial interface ISourceExpressionContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable SourceExpression
        {
            get;
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ISourceExpressionContainerBuilder ToBuilder();
    }
    public partial interface IStringComparisonContainer
    {
        System.StringComparison StringComparison
        {
            get;
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.IStringComparisonContainerBuilder ToBuilder();
    }
    public partial interface ITwoBoundariesExpressionContainer
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable LowerBoundExpression
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable UpperBoundExpression
        {
            get;
        }

        CrossCutting.Utilities.QueryEvaluator.Abstractions.Builders.ITwoBoundariesExpressionContainerBuilder ToBuilder();
    }
}
#nullable disable
