namespace CrossCutting.Utilities.ExpressionEvaluator.Extensions;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddExpressionEvaluator(this IServiceCollection services)
        => services
            .AddSingleton<IDateTimeProvider, DateTimeProvider>()
            .AddSingleton<IExpressionEvaluator, ExpressionEvaluator>()
            .AddSingleton<IExpressionComponent, DotExpressionComponent>()
            .AddSingleton<IExpressionComponent, FunctionExpressionComponent>()
            .AddSingleton<IExpressionComponent, IndexerExpressionComponent>()
            .AddSingleton<IExpressionComponent, InterpolatedStringExpressionComponent>()
            .AddSingleton<IExpressionComponent, NumericExpressionComponent>()
            .AddSingleton<IExpressionComponent, PrimitiveExpressionComponent>()
            .AddSingleton<IExpressionComponent, StateExpressionComponent>()
            .AddSingleton<IExpressionComponent, StringExpressionComponent>()
            .AddSingleton<IExpressionComponent, TypeOfExpressionComponent>()
            .AddSingleton<IFunctionCallArgumentValidator, FunctionCallArgumentValidator>()
            .AddSingleton<IFunctionDescriptorMapper, FunctionDescriptorMapper>()
            .AddSingleton<IFunctionDescriptorProvider, FunctionDescriptorProvider>()
            .AddSingleton<IFunctionParser, FunctionParser>()
            .AddSingleton<IFunctionResolver, FunctionResolver>()
            .AddSingleton<IExpressionTokenizer, ExpressionTokenizer>()
            .AddSingleton<IExpressionParser, ExpressionParser>()
            .AddSingleton<IFunction, AddDaysFunction>()
            .AddSingleton<IFunction, AddHoursFunction>()
            .AddSingleton<IFunction, AddMinutesFunction>()
            .AddSingleton<IFunction, AddMonthsFunction>()
            .AddSingleton<IFunction, AddSecondsFunction>()
            .AddSingleton<IFunction, AddYearsFunction>()
            .AddSingleton<IFunction, CastFunction>()
            .AddSingleton<IFunction, ConvertFunction>()
            .AddSingleton<IFunction, DateFunction>()
            .AddSingleton<IFunction, DatePartFunction>()
            .AddSingleton<IFunction, DateTimeFunction>()
            .AddSingleton<IFunction, IsNullFunction>()
            .AddSingleton<IFunction, LeftFunction>()
            .AddSingleton<IFunction, RightFunction>()
            .AddSingleton<IFunction, SubstringFunction>()
            .AddSingleton<IFunction, ToCamelCaseFunction>()
            .AddSingleton<IFunction, ToLowerCaseFunction>()
            .AddSingleton<IFunction, ToPascalCaseFunction>()
            .AddSingleton<IFunction, ToStringFunction>()
            .AddSingleton<IFunction, ToUpperCaseFunction>();
}
