namespace CrossCutting.Utilities.ExpressionEvaluator.Extensions;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddExpressionEvaluator(this IServiceCollection services)
        => services
            .AddSingleton<IDateTimeProvider, DateTimeProvider>()
            .AddSingleton<IExpressionEvaluator, ExpressionEvaluator>()
            .AddSingleton<IExpressionComponent, DotExpressionComponent>()
            .AddSingleton<IExpressionComponent, FunctionExpressionComponent>()
            .AddSingleton<IExpressionComponent, IndexerExpressionComponent>()
            .AddSingleton<IExpressionComponent, InterpolatedStringExpressionComponent>()
            .AddSingleton<IExpressionComponent, NumericExpressionComponent>()
            .AddSingleton<IExpressionComponent, PrimitiveExpressionComponent>()
            .AddSingleton<IExpressionComponent, StateExpressionComponent>()
            .AddSingleton<IExpressionComponent, StringExpressionComponent>()
            .AddSingleton<IExpressionComponent, TypeOfExpressionComponent>()
            .AddSingleton<IDotExpressionComponent, ArrayDotExpressionComponent>()
            .AddSingleton<IDotExpressionComponent, CollectionDotExpressionComponent>()
            .AddSingleton<IDotExpressionComponent, DateTimeDotExpressionComponent>()
            .AddSingleton<IDotExpressionComponent, ObjectDotExpressionComponent>()
            .AddSingleton<IDotExpressionComponent, ReflectionMethodDotExpressionComponent>()
            .AddSingleton<IDotExpressionComponent, ReflectionPropertyDotExpressionComponent>()
            .AddSingleton<IDotExpressionComponent, StringDotExpressionComponent>()
            .AddSingleton<IMemberCallArgumentValidator, MemberCallArgumentValidator>()
            .AddSingleton<IMemberDescriptorMapper, MemberDescriptorMapper>()
            .AddSingleton<IMemberDescriptorProvider, MemberDescriptorProvider>()
            .AddSingleton<IFunctionParser, FunctionParser>()
            .AddSingleton<IMemberResolver, MemberResolver>()
            .AddSingleton<IExpressionTokenizer, ExpressionTokenizer>()
            .AddSingleton<IExpressionParser, ExpressionParser>()
            .AddSingleton<IMember, AddHoursFunction>()
            .AddSingleton<IMember, AddMinutesFunction>()
            .AddSingleton<IMember, AddMonthsFunction>()
            .AddSingleton<IMember, AddSecondsFunction>()
            .AddSingleton<IMember, AddYearsFunction>()
            .AddSingleton<IMember, CastFunction>()
            .AddSingleton<IMember, CoalesceFunction>()
            .AddSingleton<IMember, ConvertFunction>()
            .AddSingleton<IMember, CountFunction>()
            .AddSingleton<IMember, DateFunction>()
            .AddSingleton<IMember, DateTimeFunction>()
            .AddSingleton<IMember, IsNullFunction>()
            .AddSingleton<IMember, LeftFunction>()
            .AddSingleton<IMember, RightFunction>()
            .AddSingleton<IMember, MidFunction>()
            .AddSingleton<IMember, ToCamelCaseFunction>()
            .AddSingleton<IMember, ToLowerCaseFunction>()
            .AddSingleton<IMember, ToPascalCaseFunction>()
            .AddSingleton<IMember, ToUpperCaseFunction>();
}
