// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.11
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace CrossCutting.Utilities.ExpressionEvaluator.Evaluatables
{
    public partial record ContextEvaluatable : CrossCutting.Utilities.ExpressionEvaluator.EvaluatableBase, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable
    {
        public ContextEvaluatable() : base()
        {
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.ExpressionEvaluator.Builders.Evaluatables.ContextEvaluatableBuilder(CrossCutting.Utilities.ExpressionEvaluator.Evaluatables.ContextEvaluatable entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.ExpressionEvaluator.Builders.EvaluatableBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.ExpressionEvaluator.Builders.Evaluatables.ContextEvaluatableBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.ExpressionEvaluator.Builders.Evaluatables.ContextEvaluatableBuilder(this);
        }
    }
    public partial record DelegateEvaluatable : CrossCutting.Utilities.ExpressionEvaluator.EvaluatableBase, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable
    {
        public System.Func<object?> Value
        {
            get;
        }

        public DelegateEvaluatable(System.Func<object?> value) : base()
        {
            this.Value = value;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.ExpressionEvaluator.Builders.Evaluatables.DelegateEvaluatableBuilder(CrossCutting.Utilities.ExpressionEvaluator.Evaluatables.DelegateEvaluatable entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.ExpressionEvaluator.Builders.EvaluatableBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.ExpressionEvaluator.Builders.Evaluatables.DelegateEvaluatableBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.ExpressionEvaluator.Builders.Evaluatables.DelegateEvaluatableBuilder(this);
        }
    }
    public partial record EmptyEvaluatable : CrossCutting.Utilities.ExpressionEvaluator.EvaluatableBase, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable
    {
        public EmptyEvaluatable() : base()
        {
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.ExpressionEvaluator.Builders.Evaluatables.EmptyEvaluatableBuilder(CrossCutting.Utilities.ExpressionEvaluator.Evaluatables.EmptyEvaluatable entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.ExpressionEvaluator.Builders.EvaluatableBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.ExpressionEvaluator.Builders.Evaluatables.EmptyEvaluatableBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.ExpressionEvaluator.Builders.Evaluatables.EmptyEvaluatableBuilder(this);
        }
    }
    public partial record LiteralEvaluatable : CrossCutting.Utilities.ExpressionEvaluator.EvaluatableBase, CrossCutting.Utilities.ExpressionEvaluator.Abstractions.IEvaluatable
    {
        public object? Value
        {
            get;
        }

        public LiteralEvaluatable(object? value) : base()
        {
            this.Value = value;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator CrossCutting.Utilities.ExpressionEvaluator.Builders.Evaluatables.LiteralEvaluatableBuilder(CrossCutting.Utilities.ExpressionEvaluator.Evaluatables.LiteralEvaluatable entity)
        {
            return entity.ToTypedBuilder();
        }

        public override CrossCutting.Utilities.ExpressionEvaluator.Builders.EvaluatableBaseBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public CrossCutting.Utilities.ExpressionEvaluator.Builders.Evaluatables.LiteralEvaluatableBuilder ToTypedBuilder()
        {
            return new CrossCutting.Utilities.ExpressionEvaluator.Builders.Evaluatables.LiteralEvaluatableBuilder(this);
        }
    }
}
#nullable disable
