global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using CrossCutting.Commands.Abstractions;
global using CrossCutting.Common;
global using CrossCutting.Common.Abstractions;
global using CrossCutting.Common.Extensions;
global using CrossCutting.Common.Results;
