// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 8.0.10
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace CrossCutting.Utilities.Parsers
{
    public abstract partial record FunctionParseResultArgument
    {
        protected FunctionParseResultArgument()
        {
        }

        public abstract CrossCutting.Utilities.Parsers.Builders.FunctionParseResultArgumentBuilder ToBuilder();
    }
}
#nullable disable
