// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 8.0.8
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#nullable enable
namespace CrossCutting.Utilities.Parsers
{
    public partial record FunctionParseResult
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public string FunctionName
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public System.Collections.Generic.IReadOnlyCollection<CrossCutting.Utilities.Parsers.FunctionParseResultArgument> Arguments
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public System.IFormatProvider FormatProvider
        {
            get;
        }

        public object? Context
        {
            get;
        }

        public FunctionParseResult(string functionName, System.Collections.Generic.IEnumerable<CrossCutting.Utilities.Parsers.FunctionParseResultArgument> arguments, System.IFormatProvider formatProvider, object? context)
        {
            this.FunctionName = functionName;
            this.Arguments = arguments is null ? null! : new CrossCutting.Common.ReadOnlyValueCollection<CrossCutting.Utilities.Parsers.FunctionParseResultArgument>(arguments);
            this.FormatProvider = formatProvider;
            this.Context = context;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public CrossCutting.Utilities.Parsers.Builders.FunctionParseResultBuilder ToBuilder()
        {
            return new CrossCutting.Utilities.Parsers.Builders.FunctionParseResultBuilder(this);
        }
    }
}
#nullable disable
