// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 7.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CrossCutting.Utilities.Parsers
{
#nullable enable
    public partial record FunctionParseResultBase
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public string FunctionName
        {
            get;
            private set;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public System.Collections.Generic.IReadOnlyCollection<CrossCutting.Utilities.Parsers.FunctionParseResultArgument> Arguments
        {
            get
            {
                return _arguments;
            }
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public System.IFormatProvider FormatProvider
        {
            get;
            private set;
        }

        public object? Context
        {
            get;
            private set;
        }

        public FunctionParseResultBase(string functionName, System.Collections.Generic.IEnumerable<CrossCutting.Utilities.Parsers.FunctionParseResultArgument> arguments, System.IFormatProvider formatProvider, object? context)
        {
            this.FunctionName = functionName;
            _arguments = new CrossCutting.Common.ValueCollection<CrossCutting.Utilities.Parsers.FunctionParseResultArgument>(arguments);
            this.FormatProvider = formatProvider;
            this.Context = context;
        }

        private CrossCutting.Common.ValueCollection<CrossCutting.Utilities.Parsers.FunctionParseResultArgument> _arguments;
    }
#nullable restore
}

